### ISSUE TITLE
Fix frontend production build regression from static routing test

### ISSUE THREAD

**Issue by KD7CAO** [Texas-Communications-Unit/ict-branch-toolkit#142]
## Problem

The deployment of current `main` fails while building the frontend production image. The failure was introduced by the static-routing regression test added with #140/#141:

```text
tests/staticRouting.test.ts(1,30): error TS2591: Cannot find name 'node:fs'.
```

`frontend/tests/staticRouting.test.ts` imports Node's filesystem API, but `pnpm build` runs the browser-scoped TypeScript project across the frontend test tree. This causes the production frontend image build to fail before Vite can emit the application.

The same error also blocks the Container security/SBOM job.

## Required fix

- Remove the Node-dependent routing test from the frontend TypeScript project.
- Preserve equivalent automated coverage for the `/third-party/` Nginx routing rule in a test environment that legitimately has filesystem access.
- Do not broaden the browser TypeScript configuration with Node globals solely to accommodate this infrastructure test.
- Preserve the #140 map resize and Nginx static-routing production fixes unchanged.
- Verify the production frontend image can build successfully after the change.

## Deployment observation

The disk-capacity recovery added under #138/#139 worked as intended during the failed deployment: it reclaimed Docker cache and restored approximately 5.7 GiB free space. The deployment failure occurred later during `pnpm build`, not during SSH, backup, or capacity recovery.

## Boundaries

- Hotfix only; no provider, map data, attribution, API, DNS, or deployment configuration change.
- No merge or deployment without human approval.
- Work on a feature branch per `AGENTS.md`.

Related: #140, #141, #138, #139
